// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendLog(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<any>;

export function CopyText(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:any):Promise<any>;

export function GetBackendPort():Promise<number>;

export function GetLogPath():Promise<string>;

export function GetOverlayBaseUrl():Promise<string>;

export function OpenCoverFile():Promise<string>;

export function OpenLogFolder():Promise<void>;

export function ReadCoverFile(arg1:string):Promise<string>;

export function SaveCoverImage(arg1:string):Promise<string>;
