// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendLog(arg1:string):Promise<void>;

export function BroadcastOverlayStyle(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CopyText(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:main.UpdateInfo):Promise<main.UpdateInstallResult>;

export function DownloadPlaybackToFile(arg1:string,arg2:string):Promise<string>;

export function GenerateTTS(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:string):Promise<string>;

export function GetBackendPort():Promise<number>;

export function GetLogPath():Promise<string>;

export function GetNetworkDelay():Promise<number>;

export function GetOverlayBaseUrl():Promise<string>;

export function GetSharedFloatState():Promise<string>;

export function GetSharedTheme():Promise<string>;

export function GetSystemFonts():Promise<Array<string>>;

export function GetSystemStats():Promise<main.SystemStatsResult>;

export function GetTTSVoices():Promise<Array<main.TTSVoice>>;

export function IsMiniMode():Promise<boolean>;

export function LaunchMiniWindow():Promise<void>;

export function OpenCoverFile():Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenLogFolder():Promise<void>;

export function ReadCoverFile(arg1:string):Promise<string>;

export function SaveCoverImage(arg1:string):Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetMouseClickThrough(arg1:boolean):Promise<void>;

export function SetMouseClickThroughHotkey(arg1:number,arg2:number):Promise<void>;

export function SetSharedFloatState(arg1:string):Promise<void>;

export function SetSharedTheme(arg1:string):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;
