// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendLog(arg1) {
  return window['go']['main']['App']['AppendLog'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function GetBackendPort() {
  return window['go']['main']['App']['GetBackendPort']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetOverlayBaseUrl() {
  return window['go']['main']['App']['GetOverlayBaseUrl']();
}

export function OpenCoverFile() {
  return window['go']['main']['App']['OpenCoverFile']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function ReadCoverFile(arg1) {
  return window['go']['main']['App']['ReadCoverFile'](arg1);
}

export function SaveCoverImage(arg1) {
  return window['go']['main']['App']['SaveCoverImage'](arg1);
}
