// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendLog(arg1) {
  return window['go']['main']['App']['AppendLog'](arg1);
}

export function BroadcastOverlayStyle(arg1) {
  return window['go']['main']['App']['BroadcastOverlayStyle'](arg1);
}

export function BroadcastSongRequestOverlay(arg1) {
  return window['go']['main']['App']['BroadcastSongRequestOverlay'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function DownloadPlaybackToFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadPlaybackToFile'](arg1, arg2);
}

export function GenerateTTS(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GenerateTTS'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetBackendPort() {
  return window['go']['main']['App']['GetBackendPort']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetNetworkDelay() {
  return window['go']['main']['App']['GetNetworkDelay']();
}

export function GetOverlayBaseUrl() {
  return window['go']['main']['App']['GetOverlayBaseUrl']();
}

export function GetSharedFloatState() {
  return window['go']['main']['App']['GetSharedFloatState']();
}

export function GetSharedTheme() {
  return window['go']['main']['App']['GetSharedTheme']();
}

export function GetSongRequestOverlayUrl() {
  return window['go']['main']['App']['GetSongRequestOverlayUrl']();
}

export function GetSystemFonts() {
  return window['go']['main']['App']['GetSystemFonts']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GetTTSVoices() {
  return window['go']['main']['App']['GetTTSVoices']();
}

export function IsMiniMode() {
  return window['go']['main']['App']['IsMiniMode']();
}

export function LaunchMiniWindow() {
  return window['go']['main']['App']['LaunchMiniWindow']();
}

export function OpenCoverFile() {
  return window['go']['main']['App']['OpenCoverFile']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function ReadCoverFile(arg1) {
  return window['go']['main']['App']['ReadCoverFile'](arg1);
}

export function SaveCoverImage(arg1) {
  return window['go']['main']['App']['SaveCoverImage'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetMouseClickThrough(arg1) {
  return window['go']['main']['App']['SetMouseClickThrough'](arg1);
}

export function SetMouseClickThroughHotkey(arg1, arg2) {
  return window['go']['main']['App']['SetMouseClickThroughHotkey'](arg1, arg2);
}

export function SetSharedFloatState(arg1) {
  return window['go']['main']['App']['SetSharedFloatState'](arg1);
}

export function SetSharedTheme(arg1) {
  return window['go']['main']['App']['SetSharedTheme'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}
